# Page settings
baseurl = "http://thatteidlikaalsoup.team"
languageCode = "en-us"
theme = "beautifulhugo"
title = "Thatte Idli Kaal Soup"
googleAnalytics = "UA-105305610-1"

[params]
  subtitle = "A food-loving Ultimate Frisbee club from Bangalore"
  logo = "images/tiks-logo.png"
  favicon = "images/tiks-logo.ico"
  dateFormat = "January 2, 2006"
  rss = true
  commit = false
  comments = false

[author]
  email = "tiks.india.ultimate@gmail.com"
  facebook = "Thatte-Idli-Kaal-Soup-448323595322728"
  instagram = "thatteidlikaalsoup"
  # youtube = "user/username" # or channel/channelname


[[menu.main]]
    name = "About"
    url = "about/"
    weight = 1

[[menu.main]]
    name = "Masala Idli"
    url = "masala-idli/"
    weight = 2
