# This is a basic workflow to help you get started with Actions
name: Publish Site

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - uses: BSFishy/pip-action@v1
      with:
        requirements: requirements.txt
    - run: instagram-scraper -i --media-metadata --media-types='none' -d content tiks_ultimate -u ${{ secrets.IG_USERNAME }} -p ${{ secrets.IG_PASSWORD }}
    - name: Gatsby Publish
      uses: enriikke/gatsby-gh-pages-action@v2.1.1
      with:
        # A personal access token needed to push your site after it has been built.
        access-token: ${{ secrets.GH_ACCESS_TOKEN }}
        # The branch expected by GitHub to have the static files needed for your site.
        deploy-branch: gh-pages
